version: '3'

tasks:
  controller-gen:
    desc: "📦 Install controller-gen"
    env:
      GOBIN: "{{ .TASKFILE_DIR }}/bin"
    vars:
      GO_MOD_VERSION:
        sh: cat go.mod | grep -E "sigs.k8s.io/controller-tools" | cut -d ' ' -f2
    status:
      - test -s bin/controller-gen
      - ./bin/controller-gen --version | grep "{{ .GO_MOD_VERSION }}"
    cmds:
      - go install sigs.k8s.io/controller-tools/cmd/controller-gen

  golangci-lint:
    desc: "📦 Install golangci-lint"
    env:
      GOBIN: "{{ .TASKFILE_DIR }}/bin"
    vars:
      GO_MOD_VERSION:
        sh: cat go.mod | grep -E "github.com/golangci/golangci-lint" | cut -d ' ' -f2
    status:
      - test -s bin/golangci-lint
      - ./bin/golangci-lint --version | grep "{{ .GO_MOD_VERSION }}"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint
