// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"bitbucket.systematicgroup.local/itmiks/eks-anywhere-tooling/iksctl/pkg/clients/ntnxv3Client/ntnxv3models"
)

// DeleteProjectsUUIDReader is a Reader for the DeleteProjectsUUID structure.
type DeleteProjectsUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProjectsUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteProjectsUUIDAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteProjectsUUIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteProjectsUUIDAccepted creates a DeleteProjectsUUIDAccepted with default headers values
func NewDeleteProjectsUUIDAccepted() *DeleteProjectsUUIDAccepted {
	return &DeleteProjectsUUIDAccepted{}
}

/*
DeleteProjectsUUIDAccepted describes a response with status code 202, with default header values.

Request Accepted
*/
type DeleteProjectsUUIDAccepted struct {
	Payload *ntnxv3models.ProjectIntentResponse
}

// IsSuccess returns true when this delete projects Uuid accepted response has a 2xx status code
func (o *DeleteProjectsUUIDAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete projects Uuid accepted response has a 3xx status code
func (o *DeleteProjectsUUIDAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete projects Uuid accepted response has a 4xx status code
func (o *DeleteProjectsUUIDAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete projects Uuid accepted response has a 5xx status code
func (o *DeleteProjectsUUIDAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete projects Uuid accepted response a status code equal to that given
func (o *DeleteProjectsUUIDAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete projects Uuid accepted response
func (o *DeleteProjectsUUIDAccepted) Code() int {
	return 202
}

func (o *DeleteProjectsUUIDAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /projects/{uuid}][%d] deleteProjectsUuidAccepted %s", 202, payload)
}

func (o *DeleteProjectsUUIDAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /projects/{uuid}][%d] deleteProjectsUuidAccepted %s", 202, payload)
}

func (o *DeleteProjectsUUIDAccepted) GetPayload() *ntnxv3models.ProjectIntentResponse {
	return o.Payload
}

func (o *DeleteProjectsUUIDAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProjectsUUIDDefault creates a DeleteProjectsUUIDDefault with default headers values
func NewDeleteProjectsUUIDDefault(code int) *DeleteProjectsUUIDDefault {
	return &DeleteProjectsUUIDDefault{
		_statusCode: code,
	}
}

/*
DeleteProjectsUUIDDefault describes a response with status code -1, with default header values.

Internal Error
*/
type DeleteProjectsUUIDDefault struct {
	_statusCode int

	Payload *ntnxv3models.ProjectStatus
}

// IsSuccess returns true when this delete projects UUID default response has a 2xx status code
func (o *DeleteProjectsUUIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete projects UUID default response has a 3xx status code
func (o *DeleteProjectsUUIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete projects UUID default response has a 4xx status code
func (o *DeleteProjectsUUIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete projects UUID default response has a 5xx status code
func (o *DeleteProjectsUUIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete projects UUID default response a status code equal to that given
func (o *DeleteProjectsUUIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete projects UUID default response
func (o *DeleteProjectsUUIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteProjectsUUIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /projects/{uuid}][%d] DeleteProjectsUUID default %s", o._statusCode, payload)
}

func (o *DeleteProjectsUUIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /projects/{uuid}][%d] DeleteProjectsUUID default %s", o._statusCode, payload)
}

func (o *DeleteProjectsUUIDDefault) GetPayload() *ntnxv3models.ProjectStatus {
	return o.Payload
}

func (o *DeleteProjectsUUIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
