// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProjectsUUIDParams creates a new GetProjectsUUIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectsUUIDParams() *GetProjectsUUIDParams {
	return &GetProjectsUUIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectsUUIDParamsWithTimeout creates a new GetProjectsUUIDParams object
// with the ability to set a timeout on a request.
func NewGetProjectsUUIDParamsWithTimeout(timeout time.Duration) *GetProjectsUUIDParams {
	return &GetProjectsUUIDParams{
		timeout: timeout,
	}
}

// NewGetProjectsUUIDParamsWithContext creates a new GetProjectsUUIDParams object
// with the ability to set a context for a request.
func NewGetProjectsUUIDParamsWithContext(ctx context.Context) *GetProjectsUUIDParams {
	return &GetProjectsUUIDParams{
		Context: ctx,
	}
}

// NewGetProjectsUUIDParamsWithHTTPClient creates a new GetProjectsUUIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectsUUIDParamsWithHTTPClient(client *http.Client) *GetProjectsUUIDParams {
	return &GetProjectsUUIDParams{
		HTTPClient: client,
	}
}

/*
GetProjectsUUIDParams contains all the parameters to send to the API endpoint

	for the get projects UUID operation.

	Typically these are written to a http.Request.
*/
type GetProjectsUUIDParams struct {

	/* UUID.

	   The UUID of the entity.

	   Format: UUID
	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get projects UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectsUUIDParams) WithDefaults() *GetProjectsUUIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get projects UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectsUUIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get projects UUID params
func (o *GetProjectsUUIDParams) WithTimeout(timeout time.Duration) *GetProjectsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get projects UUID params
func (o *GetProjectsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get projects UUID params
func (o *GetProjectsUUIDParams) WithContext(ctx context.Context) *GetProjectsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get projects UUID params
func (o *GetProjectsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get projects UUID params
func (o *GetProjectsUUIDParams) WithHTTPClient(client *http.Client) *GetProjectsUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get projects UUID params
func (o *GetProjectsUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the get projects UUID params
func (o *GetProjectsUUIDParams) WithUUID(uuid string) *GetProjectsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get projects UUID params
func (o *GetProjectsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
