// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"bitbucket.systematicgroup.local/itmiks/eks-anywhere-tooling/iksctl/pkg/clients/ntnxv3Client/ntnxv3models"
)

// NewPostProjectsListParams creates a new PostProjectsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProjectsListParams() *PostProjectsListParams {
	return &PostProjectsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProjectsListParamsWithTimeout creates a new PostProjectsListParams object
// with the ability to set a timeout on a request.
func NewPostProjectsListParamsWithTimeout(timeout time.Duration) *PostProjectsListParams {
	return &PostProjectsListParams{
		timeout: timeout,
	}
}

// NewPostProjectsListParamsWithContext creates a new PostProjectsListParams object
// with the ability to set a context for a request.
func NewPostProjectsListParamsWithContext(ctx context.Context) *PostProjectsListParams {
	return &PostProjectsListParams{
		Context: ctx,
	}
}

// NewPostProjectsListParamsWithHTTPClient creates a new PostProjectsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProjectsListParamsWithHTTPClient(client *http.Client) *PostProjectsListParams {
	return &PostProjectsListParams{
		HTTPClient: client,
	}
}

/*
PostProjectsListParams contains all the parameters to send to the API endpoint

	for the post projects list operation.

	Typically these are written to a http.Request.
*/
type PostProjectsListParams struct {

	// GetEntitiesRequest.
	GetEntitiesRequest *ntnxv3models.ProjectListMetadata

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post projects list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectsListParams) WithDefaults() *PostProjectsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post projects list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProjectsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post projects list params
func (o *PostProjectsListParams) WithTimeout(timeout time.Duration) *PostProjectsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post projects list params
func (o *PostProjectsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post projects list params
func (o *PostProjectsListParams) WithContext(ctx context.Context) *PostProjectsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post projects list params
func (o *PostProjectsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post projects list params
func (o *PostProjectsListParams) WithHTTPClient(client *http.Client) *PostProjectsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post projects list params
func (o *PostProjectsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGetEntitiesRequest adds the getEntitiesRequest to the post projects list params
func (o *PostProjectsListParams) WithGetEntitiesRequest(getEntitiesRequest *ntnxv3models.ProjectListMetadata) *PostProjectsListParams {
	o.SetGetEntitiesRequest(getEntitiesRequest)
	return o
}

// SetGetEntitiesRequest adds the getEntitiesRequest to the post projects list params
func (o *PostProjectsListParams) SetGetEntitiesRequest(getEntitiesRequest *ntnxv3models.ProjectListMetadata) {
	o.GetEntitiesRequest = getEntitiesRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostProjectsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.GetEntitiesRequest != nil {
		if err := r.SetBodyParam(o.GetEntitiesRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
