apiVersion: iksctl.kubematic.io/v1alpha1
kind: AirgapConfig
ociRepo:
  host: iks-harbor-base.systematicgroup.local
  repository: isovalent/cilium
  pwdbCredentialID: 23114
charts:
  - repo: "https://helm.cilium.io/"
    name: "cilium"
    version: "1.17.4"
