apiVersion: iksctl.kubematic.io/v1alpha1
kind: AirgapConfig
ociRepo:
  host: iks-harbor-base.systematicgroup.local
  repository: iks-library
  pwdbCredentialID: 23114
charts:
  - repo: "https://dell.github.io/helm-charts"
    name: "csi-powerstore"
    version: "2.13.0"