// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteProjectsUUIDParams creates a new DeleteProjectsUUIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectsUUIDParams() *DeleteProjectsUUIDParams {
	return &DeleteProjectsUUIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectsUUIDParamsWithTimeout creates a new DeleteProjectsUUIDParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectsUUIDParamsWithTimeout(timeout time.Duration) *DeleteProjectsUUIDParams {
	return &DeleteProjectsUUIDParams{
		timeout: timeout,
	}
}

// NewDeleteProjectsUUIDParamsWithContext creates a new DeleteProjectsUUIDParams object
// with the ability to set a context for a request.
func NewDeleteProjectsUUIDParamsWithContext(ctx context.Context) *DeleteProjectsUUIDParams {
	return &DeleteProjectsUUIDParams{
		Context: ctx,
	}
}

// NewDeleteProjectsUUIDParamsWithHTTPClient creates a new DeleteProjectsUUIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectsUUIDParamsWithHTTPClient(client *http.Client) *DeleteProjectsUUIDParams {
	return &DeleteProjectsUUIDParams{
		HTTPClient: client,
	}
}

/*
DeleteProjectsUUIDParams contains all the parameters to send to the API endpoint

	for the delete projects UUID operation.

	Typically these are written to a http.Request.
*/
type DeleteProjectsUUIDParams struct {

	/* UUID.

	   The UUID of the entity.

	   Format: UUID
	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete projects UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectsUUIDParams) WithDefaults() *DeleteProjectsUUIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete projects UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectsUUIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) WithTimeout(timeout time.Duration) *DeleteProjectsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) WithContext(ctx context.Context) *DeleteProjectsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) WithHTTPClient(client *http.Client) *DeleteProjectsUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) WithUUID(uuid string) *DeleteProjectsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete projects UUID params
func (o *DeleteProjectsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
