// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"bitbucket.systematicgroup.local/itmiks/eks-anywhere-tooling/iksctl/pkg/clients/ntnxv3Client/ntnxv3models"
)

// GetProjectsUUIDReader is a Reader for the GetProjectsUUID structure.
type GetProjectsUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectsUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectsUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProjectsUUIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProjectsUUIDOK creates a GetProjectsUUIDOK with default headers values
func NewGetProjectsUUIDOK() *GetProjectsUUIDOK {
	return &GetProjectsUUIDOK{}
}

/*
GetProjectsUUIDOK describes a response with status code 200, with default header values.

Success
*/
type GetProjectsUUIDOK struct {
	Payload *ntnxv3models.ProjectIntentResponse
}

// IsSuccess returns true when this get projects Uuid o k response has a 2xx status code
func (o *GetProjectsUUIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get projects Uuid o k response has a 3xx status code
func (o *GetProjectsUUIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get projects Uuid o k response has a 4xx status code
func (o *GetProjectsUUIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get projects Uuid o k response has a 5xx status code
func (o *GetProjectsUUIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get projects Uuid o k response a status code equal to that given
func (o *GetProjectsUUIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get projects Uuid o k response
func (o *GetProjectsUUIDOK) Code() int {
	return 200
}

func (o *GetProjectsUUIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{uuid}][%d] getProjectsUuidOK %s", 200, payload)
}

func (o *GetProjectsUUIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{uuid}][%d] getProjectsUuidOK %s", 200, payload)
}

func (o *GetProjectsUUIDOK) GetPayload() *ntnxv3models.ProjectIntentResponse {
	return o.Payload
}

func (o *GetProjectsUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectsUUIDDefault creates a GetProjectsUUIDDefault with default headers values
func NewGetProjectsUUIDDefault(code int) *GetProjectsUUIDDefault {
	return &GetProjectsUUIDDefault{
		_statusCode: code,
	}
}

/*
GetProjectsUUIDDefault describes a response with status code -1, with default header values.

Internal Error
*/
type GetProjectsUUIDDefault struct {
	_statusCode int

	Payload *ntnxv3models.ProjectStatus
}

// IsSuccess returns true when this get projects UUID default response has a 2xx status code
func (o *GetProjectsUUIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get projects UUID default response has a 3xx status code
func (o *GetProjectsUUIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get projects UUID default response has a 4xx status code
func (o *GetProjectsUUIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get projects UUID default response has a 5xx status code
func (o *GetProjectsUUIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get projects UUID default response a status code equal to that given
func (o *GetProjectsUUIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get projects UUID default response
func (o *GetProjectsUUIDDefault) Code() int {
	return o._statusCode
}

func (o *GetProjectsUUIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{uuid}][%d] GetProjectsUUID default %s", o._statusCode, payload)
}

func (o *GetProjectsUUIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{uuid}][%d] GetProjectsUUID default %s", o._statusCode, payload)
}

func (o *GetProjectsUUIDDefault) GetPayload() *ntnxv3models.ProjectStatus {
	return o.Payload
}

func (o *GetProjectsUUIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
