// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"bitbucket.systematicgroup.local/itmiks/eks-anywhere-tooling/iksctl/pkg/clients/ntnxv3Client/ntnxv3models"
)

// PostProjectsListReader is a Reader for the PostProjectsList structure.
type PostProjectsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostProjectsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostProjectsListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostProjectsListOK creates a PostProjectsListOK with default headers values
func NewPostProjectsListOK() *PostProjectsListOK {
	return &PostProjectsListOK{}
}

/*
PostProjectsListOK describes a response with status code 200, with default header values.

Success
*/
type PostProjectsListOK struct {
	Payload *ntnxv3models.ProjectListIntentResponse
}

// IsSuccess returns true when this post projects list o k response has a 2xx status code
func (o *PostProjectsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post projects list o k response has a 3xx status code
func (o *PostProjectsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post projects list o k response has a 4xx status code
func (o *PostProjectsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post projects list o k response has a 5xx status code
func (o *PostProjectsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post projects list o k response a status code equal to that given
func (o *PostProjectsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post projects list o k response
func (o *PostProjectsListOK) Code() int {
	return 200
}

func (o *PostProjectsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects/list][%d] postProjectsListOK %s", 200, payload)
}

func (o *PostProjectsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects/list][%d] postProjectsListOK %s", 200, payload)
}

func (o *PostProjectsListOK) GetPayload() *ntnxv3models.ProjectListIntentResponse {
	return o.Payload
}

func (o *PostProjectsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectListIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProjectsListDefault creates a PostProjectsListDefault with default headers values
func NewPostProjectsListDefault(code int) *PostProjectsListDefault {
	return &PostProjectsListDefault{
		_statusCode: code,
	}
}

/*
PostProjectsListDefault describes a response with status code -1, with default header values.

Internal Error
*/
type PostProjectsListDefault struct {
	_statusCode int

	Payload *ntnxv3models.ProjectStatus
}

// IsSuccess returns true when this post projects list default response has a 2xx status code
func (o *PostProjectsListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post projects list default response has a 3xx status code
func (o *PostProjectsListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post projects list default response has a 4xx status code
func (o *PostProjectsListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post projects list default response has a 5xx status code
func (o *PostProjectsListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post projects list default response a status code equal to that given
func (o *PostProjectsListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post projects list default response
func (o *PostProjectsListDefault) Code() int {
	return o._statusCode
}

func (o *PostProjectsListDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects/list][%d] PostProjectsList default %s", o._statusCode, payload)
}

func (o *PostProjectsListDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects/list][%d] PostProjectsList default %s", o._statusCode, payload)
}

func (o *PostProjectsListDefault) GetPayload() *ntnxv3models.ProjectStatus {
	return o.Payload
}

func (o *PostProjectsListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
