// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"bitbucket.systematicgroup.local/itmiks/eks-anywhere-tooling/iksctl/pkg/clients/ntnxv3Client/ntnxv3models"
)

// PostProjectsReader is a Reader for the PostProjects structure.
type PostProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPostProjectsAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostProjectsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostProjectsAccepted creates a PostProjectsAccepted with default headers values
func NewPostProjectsAccepted() *PostProjectsAccepted {
	return &PostProjectsAccepted{}
}

/*
PostProjectsAccepted describes a response with status code 202, with default header values.

Request Accepted
*/
type PostProjectsAccepted struct {
	Payload *ntnxv3models.ProjectIntentResponse
}

// IsSuccess returns true when this post projects accepted response has a 2xx status code
func (o *PostProjectsAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post projects accepted response has a 3xx status code
func (o *PostProjectsAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post projects accepted response has a 4xx status code
func (o *PostProjectsAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this post projects accepted response has a 5xx status code
func (o *PostProjectsAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this post projects accepted response a status code equal to that given
func (o *PostProjectsAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the post projects accepted response
func (o *PostProjectsAccepted) Code() int {
	return 202
}

func (o *PostProjectsAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects][%d] postProjectsAccepted %s", 202, payload)
}

func (o *PostProjectsAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects][%d] postProjectsAccepted %s", 202, payload)
}

func (o *PostProjectsAccepted) GetPayload() *ntnxv3models.ProjectIntentResponse {
	return o.Payload
}

func (o *PostProjectsAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProjectsDefault creates a PostProjectsDefault with default headers values
func NewPostProjectsDefault(code int) *PostProjectsDefault {
	return &PostProjectsDefault{
		_statusCode: code,
	}
}

/*
PostProjectsDefault describes a response with status code -1, with default header values.

Internal Error
*/
type PostProjectsDefault struct {
	_statusCode int

	Payload *ntnxv3models.ProjectStatus
}

// IsSuccess returns true when this post projects default response has a 2xx status code
func (o *PostProjectsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post projects default response has a 3xx status code
func (o *PostProjectsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post projects default response has a 4xx status code
func (o *PostProjectsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post projects default response has a 5xx status code
func (o *PostProjectsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post projects default response a status code equal to that given
func (o *PostProjectsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post projects default response
func (o *PostProjectsDefault) Code() int {
	return o._statusCode
}

func (o *PostProjectsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects][%d] PostProjects default %s", o._statusCode, payload)
}

func (o *PostProjectsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /projects][%d] PostProjects default %s", o._statusCode, payload)
}

func (o *PostProjectsDefault) GetPayload() *ntnxv3models.ProjectStatus {
	return o.Payload
}

func (o *PostProjectsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
