// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"bitbucket.systematicgroup.local/itmiks/eks-anywhere-tooling/iksctl/pkg/clients/ntnxv3Client/ntnxv3models"
)

// NewPutProjectsUUIDParams creates a new PutProjectsUUIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutProjectsUUIDParams() *PutProjectsUUIDParams {
	return &PutProjectsUUIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutProjectsUUIDParamsWithTimeout creates a new PutProjectsUUIDParams object
// with the ability to set a timeout on a request.
func NewPutProjectsUUIDParamsWithTimeout(timeout time.Duration) *PutProjectsUUIDParams {
	return &PutProjectsUUIDParams{
		timeout: timeout,
	}
}

// NewPutProjectsUUIDParamsWithContext creates a new PutProjectsUUIDParams object
// with the ability to set a context for a request.
func NewPutProjectsUUIDParamsWithContext(ctx context.Context) *PutProjectsUUIDParams {
	return &PutProjectsUUIDParams{
		Context: ctx,
	}
}

// NewPutProjectsUUIDParamsWithHTTPClient creates a new PutProjectsUUIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutProjectsUUIDParamsWithHTTPClient(client *http.Client) *PutProjectsUUIDParams {
	return &PutProjectsUUIDParams{
		HTTPClient: client,
	}
}

/*
PutProjectsUUIDParams contains all the parameters to send to the API endpoint

	for the put projects UUID operation.

	Typically these are written to a http.Request.
*/
type PutProjectsUUIDParams struct {

	/* Body.

	   The entity used to create or modify a project.
	*/
	Body *ntnxv3models.ProjectIntentInput

	/* UUID.

	   The UUID of the entity.

	   Format: UUID
	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put projects UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectsUUIDParams) WithDefaults() *PutProjectsUUIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put projects UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutProjectsUUIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put projects UUID params
func (o *PutProjectsUUIDParams) WithTimeout(timeout time.Duration) *PutProjectsUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put projects UUID params
func (o *PutProjectsUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put projects UUID params
func (o *PutProjectsUUIDParams) WithContext(ctx context.Context) *PutProjectsUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put projects UUID params
func (o *PutProjectsUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put projects UUID params
func (o *PutProjectsUUIDParams) WithHTTPClient(client *http.Client) *PutProjectsUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put projects UUID params
func (o *PutProjectsUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put projects UUID params
func (o *PutProjectsUUIDParams) WithBody(body *ntnxv3models.ProjectIntentInput) *PutProjectsUUIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put projects UUID params
func (o *PutProjectsUUIDParams) SetBody(body *ntnxv3models.ProjectIntentInput) {
	o.Body = body
}

// WithUUID adds the uuid to the put projects UUID params
func (o *PutProjectsUUIDParams) WithUUID(uuid string) *PutProjectsUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the put projects UUID params
func (o *PutProjectsUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *PutProjectsUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
