// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3ClientProjects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"bitbucket.systematicgroup.local/itmiks/eks-anywhere-tooling/iksctl/pkg/clients/ntnxv3Client/ntnxv3models"
)

// PutProjectsUUIDReader is a Reader for the PutProjectsUUID structure.
type PutProjectsUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutProjectsUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPutProjectsUUIDAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutProjectsUUIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutProjectsUUIDAccepted creates a PutProjectsUUIDAccepted with default headers values
func NewPutProjectsUUIDAccepted() *PutProjectsUUIDAccepted {
	return &PutProjectsUUIDAccepted{}
}

/*
PutProjectsUUIDAccepted describes a response with status code 202, with default header values.

Request Accepted
*/
type PutProjectsUUIDAccepted struct {
	Payload *ntnxv3models.ProjectIntentResponse
}

// IsSuccess returns true when this put projects Uuid accepted response has a 2xx status code
func (o *PutProjectsUUIDAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put projects Uuid accepted response has a 3xx status code
func (o *PutProjectsUUIDAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put projects Uuid accepted response has a 4xx status code
func (o *PutProjectsUUIDAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this put projects Uuid accepted response has a 5xx status code
func (o *PutProjectsUUIDAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this put projects Uuid accepted response a status code equal to that given
func (o *PutProjectsUUIDAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the put projects Uuid accepted response
func (o *PutProjectsUUIDAccepted) Code() int {
	return 202
}

func (o *PutProjectsUUIDAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{uuid}][%d] putProjectsUuidAccepted %s", 202, payload)
}

func (o *PutProjectsUUIDAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{uuid}][%d] putProjectsUuidAccepted %s", 202, payload)
}

func (o *PutProjectsUUIDAccepted) GetPayload() *ntnxv3models.ProjectIntentResponse {
	return o.Payload
}

func (o *PutProjectsUUIDAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectIntentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutProjectsUUIDDefault creates a PutProjectsUUIDDefault with default headers values
func NewPutProjectsUUIDDefault(code int) *PutProjectsUUIDDefault {
	return &PutProjectsUUIDDefault{
		_statusCode: code,
	}
}

/*
PutProjectsUUIDDefault describes a response with status code -1, with default header values.

Internal Error
*/
type PutProjectsUUIDDefault struct {
	_statusCode int

	Payload *ntnxv3models.ProjectStatus
}

// IsSuccess returns true when this put projects UUID default response has a 2xx status code
func (o *PutProjectsUUIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put projects UUID default response has a 3xx status code
func (o *PutProjectsUUIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put projects UUID default response has a 4xx status code
func (o *PutProjectsUUIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put projects UUID default response has a 5xx status code
func (o *PutProjectsUUIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put projects UUID default response a status code equal to that given
func (o *PutProjectsUUIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put projects UUID default response
func (o *PutProjectsUUIDDefault) Code() int {
	return o._statusCode
}

func (o *PutProjectsUUIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{uuid}][%d] PutProjectsUUID default %s", o._statusCode, payload)
}

func (o *PutProjectsUUIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{uuid}][%d] PutProjectsUUID default %s", o._statusCode, payload)
}

func (o *PutProjectsUUIDDefault) GetPayload() *ntnxv3models.ProjectStatus {
	return o.Payload
}

func (o *PutProjectsUUIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ntnxv3models.ProjectStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
