// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectDefStatus Project Resource Status
//
// A Project resource.
//
// swagger:model project_def_status
type ProjectDefStatus struct {

	// Project description.
	Description string `json:"description,omitempty"`

	// message list
	MessageList []*MessageResource `json:"message_list"`

	// Project name.
	// Required: true
	Name *string `json:"name"`

	// resources
	// Required: true
	Resources *ProjectDefStatusResources `json:"resources"`

	// The state of the project entity.
	State string `json:"state,omitempty"`
}

// Validate validates this project def status
func (m *ProjectDefStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessageList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectDefStatus) validateMessageList(formats strfmt.Registry) error {
	if swag.IsZero(m.MessageList) { // not required
		return nil
	}

	for i := 0; i < len(m.MessageList); i++ {
		if swag.IsZero(m.MessageList[i]) { // not required
			continue
		}

		if m.MessageList[i] != nil {
			if err := m.MessageList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("message_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("message_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatus) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ProjectDefStatus) validateResources(formats strfmt.Registry) error {

	if err := validate.Required("resources", "body", m.Resources); err != nil {
		return err
	}

	if m.Resources != nil {
		if err := m.Resources.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this project def status based on the context it is used
func (m *ProjectDefStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMessageList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResources(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectDefStatus) contextValidateMessageList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MessageList); i++ {

		if m.MessageList[i] != nil {

			if swag.IsZero(m.MessageList[i]) { // not required
				return nil
			}

			if err := m.MessageList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("message_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("message_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatus) contextValidateResources(ctx context.Context, formats strfmt.Registry) error {

	if m.Resources != nil {

		if err := m.Resources.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProjectDefStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectDefStatus) UnmarshalBinary(b []byte) error {
	var res ProjectDefStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ProjectDefStatusResources Project Resources
//
// swagger:model ProjectDefStatusResources
type ProjectDefStatusResources struct {

	// List of accounts associated with the project.
	AccountReferenceList []*AccountReference `json:"account_reference_list"`

	// List of clusters associated with the project.
	ClusterReferenceList []*ClusterReference `json:"cluster_reference_list"`

	// Optional default environment if one is specified
	DefaultEnvironmentReference *EnvironmentReference `json:"default_environment_reference,omitempty"`

	// Optional default subnet if one is specified
	DefaultSubnetReference *SubnetReference `json:"default_subnet_reference,omitempty"`

	// List of directory references in the project
	DirectoryReferenceList []*DirectoryReference `json:"directory_reference_list"`

	// Indicates AD/IDP whitelisting
	EnableDirectoryAndIdentityProviderWhitelist bool `json:"enable_directory_and_identity_provider_whitelist,omitempty"`

	// List of environments associated with the project.
	EnvironmentReferenceList []*EnvironmentReference `json:"environment_reference_list"`

	// List of external network associated with the project.
	ExternalNetworkList []*ExternalNetwork `json:"external_network_list"`

	// List of directory service groups reference. These
	// groups are not managed by Nutanix.
	//
	ExternalUserGroupReferenceList []*UserGroupReference `json:"external_user_group_reference_list"`

	// List of identity provider references in the project
	IdentityProvidersReferenceList []*IdentityProvidersReference `json:"identity_providers_reference_list"`

	// Indicates if it is the default project.
	//
	IsDefault bool `json:"is_default,omitempty"`

	// resource domain
	ResourceDomain *ResourceDomainResourcesStatus `json:"resource_domain,omitempty"`

	// List of subnets for the project.
	SubnetReferenceList []*SubnetReference `json:"subnet_reference_list"`

	// List of tunnels associated with the project.
	TunnelReferenceList []*TunnelReference `json:"tunnel_reference_list"`

	// List of users added directly to the project.
	//
	UserReferenceList []*UserReference `json:"user_reference_list"`

	// List of VPCs associated with the project.
	VpcReferenceList []*VpcReference `json:"vpc_reference_list"`
}

// Validate validates this project def status resources
func (m *ProjectDefStatusResources) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDefaultEnvironmentReference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDefaultSubnetReference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDirectoryReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnvironmentReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExternalNetworkList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExternalUserGroupReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIdentityProvidersReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubnetReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTunnelReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVpcReferenceList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectDefStatusResources) validateAccountReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.AccountReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.AccountReferenceList); i++ {
		if swag.IsZero(m.AccountReferenceList[i]) { // not required
			continue
		}

		if m.AccountReferenceList[i] != nil {
			if err := m.AccountReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "account_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "account_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateClusterReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.ClusterReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.ClusterReferenceList); i++ {
		if swag.IsZero(m.ClusterReferenceList[i]) { // not required
			continue
		}

		if m.ClusterReferenceList[i] != nil {
			if err := m.ClusterReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "cluster_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "cluster_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateDefaultEnvironmentReference(formats strfmt.Registry) error {
	if swag.IsZero(m.DefaultEnvironmentReference) { // not required
		return nil
	}

	if m.DefaultEnvironmentReference != nil {
		if err := m.DefaultEnvironmentReference.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources" + "." + "default_environment_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources" + "." + "default_environment_reference")
			}
			return err
		}
	}

	return nil
}

func (m *ProjectDefStatusResources) validateDefaultSubnetReference(formats strfmt.Registry) error {
	if swag.IsZero(m.DefaultSubnetReference) { // not required
		return nil
	}

	if m.DefaultSubnetReference != nil {
		if err := m.DefaultSubnetReference.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources" + "." + "default_subnet_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources" + "." + "default_subnet_reference")
			}
			return err
		}
	}

	return nil
}

func (m *ProjectDefStatusResources) validateDirectoryReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.DirectoryReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.DirectoryReferenceList); i++ {
		if swag.IsZero(m.DirectoryReferenceList[i]) { // not required
			continue
		}

		if m.DirectoryReferenceList[i] != nil {
			if err := m.DirectoryReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "directory_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "directory_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateEnvironmentReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.EnvironmentReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.EnvironmentReferenceList); i++ {
		if swag.IsZero(m.EnvironmentReferenceList[i]) { // not required
			continue
		}

		if m.EnvironmentReferenceList[i] != nil {
			if err := m.EnvironmentReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "environment_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "environment_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateExternalNetworkList(formats strfmt.Registry) error {
	if swag.IsZero(m.ExternalNetworkList) { // not required
		return nil
	}

	for i := 0; i < len(m.ExternalNetworkList); i++ {
		if swag.IsZero(m.ExternalNetworkList[i]) { // not required
			continue
		}

		if m.ExternalNetworkList[i] != nil {
			if err := m.ExternalNetworkList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "external_network_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "external_network_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateExternalUserGroupReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.ExternalUserGroupReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.ExternalUserGroupReferenceList); i++ {
		if swag.IsZero(m.ExternalUserGroupReferenceList[i]) { // not required
			continue
		}

		if m.ExternalUserGroupReferenceList[i] != nil {
			if err := m.ExternalUserGroupReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "external_user_group_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "external_user_group_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateIdentityProvidersReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.IdentityProvidersReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.IdentityProvidersReferenceList); i++ {
		if swag.IsZero(m.IdentityProvidersReferenceList[i]) { // not required
			continue
		}

		if m.IdentityProvidersReferenceList[i] != nil {
			if err := m.IdentityProvidersReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "identity_providers_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "identity_providers_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateResourceDomain(formats strfmt.Registry) error {
	if swag.IsZero(m.ResourceDomain) { // not required
		return nil
	}

	if m.ResourceDomain != nil {
		if err := m.ResourceDomain.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources" + "." + "resource_domain")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources" + "." + "resource_domain")
			}
			return err
		}
	}

	return nil
}

func (m *ProjectDefStatusResources) validateSubnetReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.SubnetReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.SubnetReferenceList); i++ {
		if swag.IsZero(m.SubnetReferenceList[i]) { // not required
			continue
		}

		if m.SubnetReferenceList[i] != nil {
			if err := m.SubnetReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "subnet_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "subnet_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateTunnelReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.TunnelReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.TunnelReferenceList); i++ {
		if swag.IsZero(m.TunnelReferenceList[i]) { // not required
			continue
		}

		if m.TunnelReferenceList[i] != nil {
			if err := m.TunnelReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "tunnel_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "tunnel_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateUserReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.UserReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.UserReferenceList); i++ {
		if swag.IsZero(m.UserReferenceList[i]) { // not required
			continue
		}

		if m.UserReferenceList[i] != nil {
			if err := m.UserReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "user_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "user_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) validateVpcReferenceList(formats strfmt.Registry) error {
	if swag.IsZero(m.VpcReferenceList) { // not required
		return nil
	}

	for i := 0; i < len(m.VpcReferenceList); i++ {
		if swag.IsZero(m.VpcReferenceList[i]) { // not required
			continue
		}

		if m.VpcReferenceList[i] != nil {
			if err := m.VpcReferenceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "vpc_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "vpc_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this project def status resources based on the context it is used
func (m *ProjectDefStatusResources) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccountReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClusterReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDefaultEnvironmentReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDefaultSubnetReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDirectoryReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEnvironmentReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExternalNetworkList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExternalUserGroupReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIdentityProvidersReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResourceDomain(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSubnetReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTunnelReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVpcReferenceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectDefStatusResources) contextValidateAccountReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AccountReferenceList); i++ {

		if m.AccountReferenceList[i] != nil {

			if swag.IsZero(m.AccountReferenceList[i]) { // not required
				return nil
			}

			if err := m.AccountReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "account_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "account_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateClusterReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ClusterReferenceList); i++ {

		if m.ClusterReferenceList[i] != nil {

			if swag.IsZero(m.ClusterReferenceList[i]) { // not required
				return nil
			}

			if err := m.ClusterReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "cluster_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "cluster_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateDefaultEnvironmentReference(ctx context.Context, formats strfmt.Registry) error {

	if m.DefaultEnvironmentReference != nil {

		if swag.IsZero(m.DefaultEnvironmentReference) { // not required
			return nil
		}

		if err := m.DefaultEnvironmentReference.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources" + "." + "default_environment_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources" + "." + "default_environment_reference")
			}
			return err
		}
	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateDefaultSubnetReference(ctx context.Context, formats strfmt.Registry) error {

	if m.DefaultSubnetReference != nil {

		if swag.IsZero(m.DefaultSubnetReference) { // not required
			return nil
		}

		if err := m.DefaultSubnetReference.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources" + "." + "default_subnet_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources" + "." + "default_subnet_reference")
			}
			return err
		}
	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateDirectoryReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DirectoryReferenceList); i++ {

		if m.DirectoryReferenceList[i] != nil {

			if swag.IsZero(m.DirectoryReferenceList[i]) { // not required
				return nil
			}

			if err := m.DirectoryReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "directory_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "directory_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateEnvironmentReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EnvironmentReferenceList); i++ {

		if m.EnvironmentReferenceList[i] != nil {

			if swag.IsZero(m.EnvironmentReferenceList[i]) { // not required
				return nil
			}

			if err := m.EnvironmentReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "environment_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "environment_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateExternalNetworkList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ExternalNetworkList); i++ {

		if m.ExternalNetworkList[i] != nil {

			if swag.IsZero(m.ExternalNetworkList[i]) { // not required
				return nil
			}

			if err := m.ExternalNetworkList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "external_network_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "external_network_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateExternalUserGroupReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ExternalUserGroupReferenceList); i++ {

		if m.ExternalUserGroupReferenceList[i] != nil {

			if swag.IsZero(m.ExternalUserGroupReferenceList[i]) { // not required
				return nil
			}

			if err := m.ExternalUserGroupReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "external_user_group_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "external_user_group_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateIdentityProvidersReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.IdentityProvidersReferenceList); i++ {

		if m.IdentityProvidersReferenceList[i] != nil {

			if swag.IsZero(m.IdentityProvidersReferenceList[i]) { // not required
				return nil
			}

			if err := m.IdentityProvidersReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "identity_providers_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "identity_providers_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateResourceDomain(ctx context.Context, formats strfmt.Registry) error {

	if m.ResourceDomain != nil {

		if swag.IsZero(m.ResourceDomain) { // not required
			return nil
		}

		if err := m.ResourceDomain.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources" + "." + "resource_domain")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resources" + "." + "resource_domain")
			}
			return err
		}
	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateSubnetReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SubnetReferenceList); i++ {

		if m.SubnetReferenceList[i] != nil {

			if swag.IsZero(m.SubnetReferenceList[i]) { // not required
				return nil
			}

			if err := m.SubnetReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "subnet_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "subnet_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateTunnelReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TunnelReferenceList); i++ {

		if m.TunnelReferenceList[i] != nil {

			if swag.IsZero(m.TunnelReferenceList[i]) { // not required
				return nil
			}

			if err := m.TunnelReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "tunnel_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "tunnel_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateUserReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.UserReferenceList); i++ {

		if m.UserReferenceList[i] != nil {

			if swag.IsZero(m.UserReferenceList[i]) { // not required
				return nil
			}

			if err := m.UserReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "user_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "user_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ProjectDefStatusResources) contextValidateVpcReferenceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.VpcReferenceList); i++ {

		if m.VpcReferenceList[i] != nil {

			if swag.IsZero(m.VpcReferenceList[i]) { // not required
				return nil
			}

			if err := m.VpcReferenceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resources" + "." + "vpc_reference_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resources" + "." + "vpc_reference_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProjectDefStatusResources) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectDefStatusResources) UnmarshalBinary(b []byte) error {
	var res ProjectDefStatusResources
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
