// Code generated by go-swagger; DO NOT EDIT.

package ntnxv3models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectListMetadata Metadata for project list
//
// # All api calls that return a list will have this metadata block as input
//
// swagger:model project_list_metadata
type ProjectListMetadata struct {

	// The filter in FIQL syntax used for the results.
	Filter string `json:"filter,omitempty"`

	// The kind name
	Kind *string `json:"kind,omitempty"`

	// The number of records to retrieve relative to the offset
	// Minimum: 1
	Length int32 `json:"length,omitempty"`

	// Offset from the start of the entity list
	// Minimum: 0
	Offset *int32 `json:"offset,omitempty"`

	// The attribute to perform sort on
	SortAttribute string `json:"sort_attribute,omitempty"`

	// sort order
	SortOrder SortOrder `json:"sort_order,omitempty"`
}

// Validate validates this project list metadata
func (m *ProjectListMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLength(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOffset(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSortOrder(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectListMetadata) validateLength(formats strfmt.Registry) error {
	if swag.IsZero(m.Length) { // not required
		return nil
	}

	if err := validate.MinimumInt("length", "body", int64(m.Length), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *ProjectListMetadata) validateOffset(formats strfmt.Registry) error {
	if swag.IsZero(m.Offset) { // not required
		return nil
	}

	if err := validate.MinimumInt("offset", "body", int64(*m.Offset), 0, false); err != nil {
		return err
	}

	return nil
}

func (m *ProjectListMetadata) validateSortOrder(formats strfmt.Registry) error {
	if swag.IsZero(m.SortOrder) { // not required
		return nil
	}

	if err := m.SortOrder.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("sort_order")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("sort_order")
		}
		return err
	}

	return nil
}

// ContextValidate validate this project list metadata based on the context it is used
func (m *ProjectListMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSortOrder(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectListMetadata) contextValidateSortOrder(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.SortOrder) { // not required
		return nil
	}

	if err := m.SortOrder.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("sort_order")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("sort_order")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProjectListMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectListMetadata) UnmarshalBinary(b []byte) error {
	var res ProjectListMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
